controller_manager:
  ros__parameters:
    update_rate: 1  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    inputs:
     - gpio/fl_state
     - gpio/fr_state
     - gpio/bl_state
     - gpio/br_state
    outputs:
     - gpio/fl_command
     - gpio/fr_command
     - gpio/bl_command
     - gpio/br_command

		left_wheel_names: 
