controller_manager:
  ros__parameters:
    update_rate: 1  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
		left_wheel_names: ["fl", "bl"]
		right_wheel_names: ["rl", "rl"]
